package(default_visibility = ["//visibility:public"])

filegroup(
    name = "robot",
    srcs = [
        "setup.robot",
        "seg_1.stl",
        "seg_2.stl",
        "seg_2_1.stl",
        "seg_2_2.stl",
        "seg_2_3.stl",
        "seg_2_4.stl",
        "seg_2_5.stl",
        "seg_3.stl",
        "seg_4.stl",
        "seg_4_1.stl",
        "seg_4_2.stl",
        "seg_4_3.stl",
        "seg_5.stl",
        "seg_6.stl",
    ],
)
