package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cases",
    srcs = [
        "case_trivial.conf",
        "case_easy.conf",
        "case_hard.conf",
    ],
    data = [
        "//motion-planning-data/abb-irb-120/robot:robot",
        "//motion-planning-data/abb-irb-120/environment:environment",
    ],
)
