package(default_visibility = ["//visibility:public"])

filegroup(
    name = "environment",
    srcs = [
        "obstacles_trivial.stl",
        "obstacles_easy.stl",
        "obstacles_hard.stl",
    ],
)
